# Based on https://github.com/oakserver/oak/blob/v5.0.0/.github/workflows/oak-ci.yml

name: deno_minimist ci

on: [push, pull_request]

jobs:
  build:
    name: deno_minimist
    runs-on: ubuntu-latest
    env:
        CI: true
        DENO_VERSION: v1.0.2
    steps:
      - name: clone repository
        uses: actions/checkout@v2

      - name: run tests
        run: |
          curl -L https://deno.land/x/install/install.sh | sh -s $DENO_VERSION
          export PATH="$HOME/.deno/bin:$PATH"
          echo 'versions' && deno --version
          deno test